<table border="1">
    <?php
        $a=$_GET["coluna"];
        $b=$_GET["linha"];
        if($_SESSION["tabuleiro"][$b][$a]==''){
            $_SESSION["tabuleiro"][$b][$a] = $_GET["simbolo"];
        }else{
            if($_SESSION["jogada"][0]==2){
                $_SESSION["jogada"][0]=1;
                header("Location:indexjogo.php");
            }else{
                $_SESSION["jogada"][0]=2;
                header("Location:indexjogo.php");
            }
        }
        ?>
    <thead>
        <tr>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
        </tr>
    </thead>
    <?php 
    echo'
    <tbody>
        <tr>
            <th>0</th>
            <td>'.$_SESSION["tabuleiro"][0][0].'</td>
            <td>'.$_SESSION["tabuleiro"][0][1].'</td>
            <td>'.$_SESSION["tabuleiro"][0][2].'</td>
        <tr>
        <tr>
            <th>1</th>
            <td>'.$_SESSION["tabuleiro"][1][0].'</td>
            <td>'.$_SESSION["tabuleiro"][1][1].'</td>
            <td>'.$_SESSION["tabuleiro"][1][2].'</td>
        <tr>
        <tr>
            <th>2</th>
            <td>'.$_SESSION["tabuleiro"][2][0].'</td>
            <td>'.$_SESSION["tabuleiro"][2][1].'</td>
            <td>'.$_SESSION["tabuleiro"][2][2].'</td>
        <tr>
    </tbody>';?>

</table><hr>
